project:
  type: book

book:
  title: "Locality-preserving representation of *k*-mer sets"
  author:
    - name: "Igor Martayan"
      orcid: 0009-0008-3007-6168
      url: https://igor.martayan.org
  site-url: https://phd.martayan.org
  repo-url: https://github.com/imartayan/phd
  sidebar:
    title: "PhD Thesis"
  chapters:
    - index.qmd
    - part: "Notes"
      chapters:
      - notes/necklace.qmd
      - notes/hyperkmer.qmd
    - references.qmd
  draft-mode: gone

bibliography: references.bib
csl: institute-of-mathematics-and-its-applications.csl
biblatexoptions: [
  style=authoryear,
  citestyle=authoryear,
  maxcitenames=2,
  mincitenames=1,
  maxbibnames=99,
]

format:
  html:
    theme: cosmo
    html-math-method: katex
    include-in-header: preamble.html
    link-external-newwindow: true
    smooth-scroll: true
    strip-comments: true
  pdf:
    pdf-engine: xelatex
    cite-method: biblatex
    documentclass: scrreprt
    include-in-header: preamble.tex
    papersize: a4

filters:
  - search-replace
  - pseudocode
  - diagram

crossref:
  lst-title: Algorithm
  lst-prefix: Algorithm

search-replace:
  /kmer: "*k*-mer"
  /mmer: "*m*-mer"
  /skmer: "super-*k*-mer"
  /hkmer: "hyper-*k*-mer"
