project:
  type: book

book:
  title: "Locality-preserving representation of k-mer sets"
  author:
    - name: "Igor Martayan"
      orcid: 0009-0008-3007-6168
      url: https://igor.martayan.org
  site-url: https://phd.martayan.org
  repo-url: https://github.com/imartayan/phd
  sidebar:
    title: "PhD Thesis"
  output-file: "thesis"
  chapters:
    - index.qmd
    - part: chapters/intro.qmd
      chapters:
      - chapters/intro-seq.qmd
      - chapters/intro-kmers.qmd
      - chapters/intro-sketching.qmd
      - chapters/intro-minimizers.qmd
    - part: chapters/hpc.qmd
      chapters:
      - chapters/intro-simd.qmd
      - chapters/simd-parsing.qmd
      - chapters/rolling-hash.qmd
      - chapters/simd-minimizers.qmd
      - chapters/filtering.qmd
      - chapters/hpc-discussion.qmd
    - part: chapters/locality.qmd
      chapters:
      - chapters/kmer-sets.qmd
      - chapters/necklaces.qmd
      - chapters/set-rep.qmd
      - chapters/skmer-map.qmd
      - chapters/skmer-sketch.qmd
      - chapters/locality-discussion.qmd
    - part: chapters/sampling.qmd
      chapters:
      - chapters/low-density-minimizers.qmd
      - chapters/multimini.qmd
      - chapters/phrases.qmd
      - chapters/lexic.qmd
      - chapters/sampling-discussion.qmd
    - chapters/discussion.qmd
    - references.qmd
  appendices:
    - appendix/simd-parsing.qmd
    - appendix/forward-canonical.qmd
  draft-mode: gone

bibliography: references.bib
csl: references.csl
biblatexoptions: [
  style=alphabetic,
  maxalphanames=4,
  maxcitenames=2,
  mincitenames=1,
  maxbibnames=99,
]

format:
  html:
    theme: cosmo
    html-math-method: katex
    include-in-header: preamble.html
    default-image-extension: svg
    syntax-highlighting: github
    link-external-newwindow: true
    smooth-scroll: true
    strip-comments: true
    lightbox: true
  pdf:
    keep-tex: true
    pdf-engine: xelatex
    cite-method: biblatex
    documentclass: scrreprt
    include-in-header: preamble.tex
    default-image-extension: pdf
    syntax-highlighting: github
    fontsize: 10pt
    sansfont: "Lato"
    monofont: "DejaVu Sans Mono"
    papersize: a4
    geometry:
      - margin=1in
    mathspec: true
    indent: true

execute:
  cache: true

filters:
  - search-replace
  - pseudocode
  - diagram

crossref:
  custom:
    - kind: float
      key: alg
      reference-prefix: "Algorithm"
      caption-prefix: "Algorithm"
      caption-location: top
      latex-env: alg
      latex-list-of-description: Algorithm

search-replace:
  /kmer: "*k*-mer"
  /mmer: "*m*-mer"
  /skmer: "super-*k*-mer"
  /hkmer: "hyper-*k*-mer"
