# Set representation and operations

:::{.callout-note}
This chapter is adapted from {{< longcite cbl >}} and {{< longcite grimr >}}.
:::

A few years ago, the feasibility of indexing comprehensive genomic or transcriptomic datasets seemed beyond reach.
However, recent advances in the indexing of large-scale biological sequence datasets have brought solutions leading to different large scale queryable indexes.
Examples include the entirety of assembled bacterial genomes [@allthebacteria], or creating a searchable, quantitative index for RNA-seq data in cancer research [@transipedia].
Various methodologies, all of them based on /kmers, have been introduced to this extent.
These methods typically represent /kmer sets in compact, compressed formats that also retain information about the origin of the /kmers.
These indexing solutions often employ structures like colored de Bruijn graphs, among others [@marchet2021data].

In essence, these structures operate by breaking down a query sequence into /kmers and by identifying intersection between the /kmer set of the query and those of the indexed datasets. While these developments have unlocked opportunities, the range of queries that can be effectively handled remains limited.
For example, current methods do not support inverse operations such as determining which /kmers are present in certain datasets but absent in others.
This capability would be particularly useful in comparative studies, such as differentiating between datasets derived from patients versus control groups.
This type of query would be more typical in databases. However, databases of /kmers are underdeveloped and notably prohibitive in construction time.

In this chapter, we introduce a new framework designed to efficiently enumerate /kmers from various datasets based on specified constraints or metadata tags. We demonstrate how to construct subsets of /kmers using these tags and how to simplify query operations to reduce computational delays.
We implement a solution using a recent /kmer set data-structure that was tailored for set operations [@cbl]. We demonstrate that our method is capable of handling thousands of datasets efficiently. To illustrate its potential applications, we present two specific case studies showcasing the type of research that can be conducted using our approach.

## Problem formulation

### References and tags

Let $\mathcal{R}=\lbrace R_1,\dots, R_N\rbrace$ be a collection of references (e.g. genomes, transcriptomes, etc.). A reference $R_i$ is a string over DNA alphabet $\Sigma = \lbrace A,C,G,T \rbrace$. A /kmer is a word on $\Sigma^k$, with $k\geq 1$ fixed. Using the notion of *spectrum* from [@rahman2021representation], we denote by $\sigma_i$ the spectrum of reference $R_i$, i.e. the set of all /kmers of $R_i$: $\sigma_i = \lbrace x \in \Sigma^k : x \in R_i \rbrace$ -- where $x\in R_i$ is to be understood as "$x$ is a substring of $R_i$". The spectrum of the collection $\mathcal{R}$ is defined as
$$\sigma(\mathcal{R}) = \lbrace x \in  \Sigma^k : \exists i\in [\![1,N]\!], x\in R_i\rbrace = \bigcup_{i=1}^N \sigma_i.$$
Since we assume the collection $\mathcal{R}$ to be fixed in the sequel of this chapter, and since $\sigma(\mathcal{R})$ denotes the set of all relevant /kmers, we shall also denote this set by $\mathcal{U}$ and refer to it as "the universe".

Now, suppose that to each reference we assign some metadata, in the form of *tags*. Typically, tags can indicate whether a given reference comes from a certain species, is diagnosed with a certain pathology, etc.

:::{#def-grimr-tag}
## Tag

Any subset $Q\subseteq \lbrace 1,\dots,N\rbrace$ is referred to as a *tag*.
:::

Tags can be labeled with strings but, for the sake of simplicity, we will use capital letters $A,B,C,\dots$ to designate tags in this chapter.

### Building /kmer sets from tags

A /kmer (binary) *index* can be seen as a relational table $I$, where the first attribute (i.e. column) corresponds to /kmers, and the subsequent attributes to the $N$ references. Each row contains a tuple $(x,b_1,\dots,b_N)$, where $x\in \mathcal{U}$ and $b_i\in \lbrace0,1\rbrace$ with $b_i=1\iff x\in R_i$. Our aim in this chapter is to propose a method for developing inverse queries on indexes, i.e. instead of querying which references a /kmer (or a set of /kmers) belongs to, we want to determine the set of /kmers whose references satisfy certain constraints on their metadata. Before building more advanced queries, the most basic /kmer sets one can seek to construct are, given a tag $Q$,

$$\begin{aligned}
\operatorname{All}(Q) &= \bigcap_{i\in Q} \sigma_i & \operatorname{Any}(Q) &= \bigcup_{i\in Q} \sigma_i\\
\operatorname{NotAll}(Q) &= \mathcal{U}\setminus \operatorname{All}(Q) & \operatorname{NotAny}(Q) &=\mathcal{U}\setminus \operatorname{Any}(Q)
\end{aligned}$$ {#eq-grimr-operator-def}

In other words, $\operatorname{All}(Q)$ represents the set of /kmers which appear in *all* the references of $Q$, whereas $\operatorname{Any}(Q)$ represents the set of /kmers which appear in *at least* one reference of $Q$. $\operatorname{NotAny}(Q)$ represents the set of /kmers which do not appear in *any* reference of $Q$; whereas $\operatorname{NotAll}(Q)$ represents the set of /kmers which do not appear *simultaneously* in all the references of $Q$.

A /kmer $x$ corresponding to the tuple $(x,b_1,\dots,b_N)$ in the table $I$ belongs to $\operatorname{All}(Q)$ if and only if $\bigwedge_{i\in Q} b_i$ and to $\operatorname{Any}(Q)$ if and only if $\bigvee_{i\in Q} b_i$. $\operatorname{NotAll}(Q)$ and $\operatorname{NotAny}(Q)$ are obtained by taking the respective negations of those formulas. In the context of relational databases, all of those sets can be built using only selection and projection operators. Recall that selection is a unary operator $\verb|Select|_\varphi(I)$, that returns the set of all tuples in $I$ that satisfy propositional formula $\varphi$; whereas projection $\verb|Project|_{a}(I)$ returns a table obtained from $I$ containing only the attribute $a$ [@codd1970relational]. Therefore, if one wanted to build the set $\operatorname{All}(Q)$, the associated query would be
$$\verb|Project|_{\text{k-mer}}\left(\verb|Select|_{\bigwedge_{i\in Q} b_i}(I)\right).$$
As simple as it is, this query is already difficult to accomplish with current tools. On the one hand, to the best of our knowledge, no /kmer indexes allow queries formulated in relational algebra, but neither do they allow to simply filter by column. On the other hand, relational database implementations do not scale easily, and none are capable of processing and storing the volumes of data resulting from sequencing. The only available option would be to choose an index whose rows can be exhaustively scanned and, for each row, check whether the associated /kmer verifies the requested constraint. The complexity of such an approach would be $O(|\mathcal{U}|\cdot N)$, which is obviously not desirable. Finally, we would also like to be able to formulate more elaborate queries!

In the broadest possible context, a query would be constructed from a Boolean formula $\varphi$ acting on the variables $b_1,\dots,b_N$, and would take the form $\verb|Project|_{\text{k-mer}}\left(\verb|Select|_{\varphi}(I)\right)$. However, as this chapter is concerned with queries constructed from reference metadata, i.e. tags, we adopt a more restricted definition, where our "basic blocks" are the operators defined above: $\operatorname{All}$, $\operatorname{Any}$, $\operatorname{NotAll}$, $\operatorname{NotAny}$. In particular, adopting this convention means that queries can be written in an almost natural language, making the approach more user-friendly (e.g. a query could be "$(\operatorname{All}(A)$ and $\operatorname{Any}(B))$ or $\operatorname{NotAll}(C)$").

A query can be expressed either with set algebra, following @eq-grimr-operator-def, or with relational algebra, as seen above. By virtue of the foregoing discussion, the relational algebra approach seems intractable. In this chapter, we explore the set-based direction, taking advantage of the recent CBL tool [@cbl], which implements a data structure for dynamically manipulating sets of /kmers. Rather than exhaustively exploring a gigantic table, we will incrementally build the set of /kmers that respond to a given query.

### From relational databases to set algebra

As announced, the queries we are interested in for this chapter are formed by operators $\operatorname{All}$, $\operatorname{Any}$, $\operatorname{NotAll}$, $\operatorname{NotAny}$, applied to tags, linked by unions, intersections, possibly nested within each other. Using standard set operations and De Morgan's laws, any query can be reduced to a standard form of the form $U_1 \cap \cdots \cap U_k$, where $U_i$ is a union of operators, or of the form $I_1 \cup \cdots \cup I_k$, where $I_i$ is an intersection of operators [@goodstein2007boolean].

:::{#rem-grimr-standard-form}
Note that the usual standard form would require elements $U_i$ or $I_k$ to be composed only of "primitive" sets, where our formulation replaces them with one of our four operators, which are themselves constructed from other sets. Our approach works because the operators $\operatorname{All}$ and $\operatorname{NotAll}$ (respectively $\operatorname{Any}$ and $\operatorname{NotAny}$) are complementary to each other: De Morgan's laws apply without needing to descend to the "lower level" of sets.
:::

However, it remains to be determined which standard form, conjunctive or disjunctive, is best suited to our problem of constructing sets of /kmers. The first point to consider is that a single reference may already be made up of several billion distinct /kmers, e.g. for the human genome. The result is that, pathological cases aside, a set $U_i$ formed from the union of several operators could be drastically larger than the final set obtained after intersection -- @fig-grimr-strategy (a); whereas, conversely, a set $I_i$ formed from the intersection of several operators is necessarily smaller than the final set obtained after union -- @fig-grimr-strategy (b).

:::{#fig-grimr-strategy}

```{.tikz}
%%| filename: grimr-strategy
%%| opt-zoom: 1.5

\usetikzlibrary{positioning}

\begin{tikzpicture}

\def\r{0.5}

\begin{scope}[xshift=-4cm]
\foreach \i in {1,...,6}
{
\draw[fill=red,fill opacity=0.15,draw=gray,rotate around={60*\i-60:(60*\i-60:1.75*\r)}] (60*\i-60:1.75*\r) ellipse (2*\r cm and \r cm);
\node at (60*\i-60:1.75*\r) {$U_\i$};
}
\draw[ultra thick,black] (0,0) circle (0.1);
\node[below=1.5cm] at (0,0) {(a) $U_1 \cap \cdots \cap U_k$};
\end{scope}

\begin{scope}[xshift=4cm]
\draw[draw=gray,fill=red,fill opacity=0.15] (0,0) circle (\r);
\node at (0,0) {$I_1$};
\foreach \i in {2,...,7}
{
\draw[fill=red,fill opacity=0.15,draw=gray] (60*\i:1.75*\r) circle (\r);
\node at (60*\i-120:1.75*\r) {$I_\i$};
}
\tikzstyle{arc}=[ultra thick,black]
\draw[arc] (30:2*\r) arc (-30:150:\r);
\draw[arc] (90:2*\r) arc (30:210:\r);
\draw[arc] (150:2*\r) arc (90:270:\r);
\draw[arc] (210:2*\r) arc (150:330:\r);
\draw[arc] (270:2*\r) arc (210:390:\r);
\draw[arc] (330:2*\r) arc (270:450:\r);
\node[below=1.5cm] at (0,0) {(b) $I_1\cup \cdots \cup I_k$};
\end{scope}

\end{tikzpicture}
```

Visual illustration of the two possible standard forms for a query and the resulting set.
:::

For our problem, therefore, it seems that choosing a disjunctive standard form is the most appropriate -- i.e. of the form $I_1\cup \cdots \cup I_k$. What is more, since the sets $I_i$, once constructed, are smaller than the final set answering the query, the only thing to check is that the construction of the $I_i$'s themselves can be done without manipulating sets that are too large compared to this final size -- this with the aim of having a method that is tractable in memory and competitive against exhaustive index exploration. Finally, we arrive at the fundamental problem that will occupy us for the rest of this chapter: efficiently calculating clauses $I_i$ that are composed of operator intersections.

:::{#def-grimr-problem}
## Problem

Provided four sets of tags $\mathcal{A}=\lbrace A_1, A_2,\dots\rbrace$, $\mathcal{B}=\lbrace B_1, B_2, \dots \rbrace$, $\mathcal{C}=\lbrace C_1, C_2, \dots \rbrace$ and $\mathcal{D}=\lbrace D_1, D_2\dots \rbrace$, build the following /kmer set:
$$\mathcal{I}(\mathcal{A},\mathcal{B},\mathcal{C},\mathcal{D}) = \left(\bigcap_{A\in \mathcal{A}} \operatorname{All}(A)\right) \cap \left(\bigcap_{B\in\mathcal{B}} \operatorname{Any}(B) \right) \cap \left(\bigcap_{C\in\mathcal{C}} \operatorname{NotAll}(C)\right) \cap \left(\bigcap_{D\in\mathcal{D}} \operatorname{NotAny}(D)\right);$$
with the understanding that if one of the sets $\mathcal{A}, \mathcal{B}, \mathcal{C}$ or $\mathcal{D}$ is empty, the associated intersection is removed; by convention $\mathcal{I}(\emptyset,\emptyset,\emptyset,\emptyset)=\emptyset$.
:::

In other words, $\mathcal{I}(\mathcal{A},\mathcal{B},\mathcal{C},\mathcal{D})$ represents the set of all /kmers in $\mathcal{U}$ that satisfy simultaneously all the required constraints associated to that particular clause. The quadruplet $(\mathcal{A},\mathcal{B},\mathcal{C},\mathcal{D})$ is referred to, somewhat abusively, as a *clause* in the sequel.

Throughout this chapter, we are going to propose a number of different reorganisations (using the usual set operations) of the way in which we write $\mathcal{I}(\mathcal{A},\mathcal{B},\mathcal{C},\mathcal{D})$, with the aim of simplifying its writing and calculation. We start by the following one.

:::{#prp-grimr-partition}

$$\mathcal{I}(\mathcal{A},\mathcal{B},\mathcal{C},\mathcal{D}) = \left(\left(\bigcap_{A\in \mathcal{A}} \operatorname{All}(A)\right) \cap \left(\bigcap_{B\in\mathcal{B}} \operatorname{Any}(B) \right)\right) \left\backslash \left(\left(\bigcup_{C\in\mathcal{C}} \operatorname{All}(C)\right) \cup \left(\bigcup_{D\in\mathcal{D}} \operatorname{Any}(D)\right)\right)\right.$$
:::

:::{.proof}
The proof derives naturally from the following manipulations, where $P$ and $Q$ are sets belonging to the same universe $\mathcal{U}$: $(\mathcal{U}\setminus P) \cap (\mathcal{U}\setminus Q) = \mathcal{U}\setminus (P\cup Q)$ and $P \cap (\mathcal{U}\setminus Q) = (P \cap \mathcal{U})\setminus Q = P\setminus Q$.
:::

With regard to @prp-grimr-partition, whenever $\mathcal{A}=\mathcal{B}=\emptyset$, the left part of $\setminus$ should be replaced by $\mathcal{U}$; whereas whenever $\mathcal{C}=\mathcal{D}=\emptyset$, the right part of $\setminus$ should be replaced by $\emptyset$. If all of them are empty sets, the solution set is also empty as per the convention of @def-grimr-problem.

A completely naive way of constructing $\mathcal{I}(\mathcal{A},\mathcal{B},\mathcal{C},\mathcal{D})$ from the preceding result would be to first construct, independently, each of the sets $\operatorname{All}(A)$, $\operatorname{Any}(B)$, $\operatorname{All}(C)$, and $\operatorname{Any}(D)$ before proceeding with their unions, intersections and differences. Clearly, this approach is not optimal, since if the same reference were to appear in several tags, it would be loaded into memory and processed as many times! More precisely, if we assume that all the references are the same size, i.e. $\forall i, |\sigma_i|=K$, and that loading a reference into memory takes $O(K)$ time, then building all these sets would require a time of
$$O\left(K\cdot \left( \sum_{A\in \mathcal{A}} |A| + \sum_{B\in \mathcal{B}} |B| + \sum_{C\in \mathcal{C}} |C| + \sum_{D\in \mathcal{D}} |D|\right)\right),$$
before any further processing. Let us define the size of a clause $(\mathcal{A},\mathcal{B},\mathcal{C},\mathcal{D})$ as the quantity

$$\textrm{size}(\mathcal{A},\mathcal{B},\mathcal{C},\mathcal{D}) = \sum_{A\in \mathcal{A}} |A| + \sum_{B\in \mathcal{B}} |B| + \sum_{C\in \mathcal{C}} |C| + \sum_{D\in \mathcal{D}} |D|.$$ {#eq-grimr-size}

In @sec-grimr-computation, we propose a less naive method for calculating $\mathcal{I}(\mathcal{A},\mathcal{B},\mathcal{C},\mathcal{D})$, that also involves the quantity $\textrm{size}(\mathcal{A},\mathcal{B},\mathcal{C},\mathcal{D})$ in its time complexity -- see @prp-grimr-construction-complexity. So, regardless of the sophistication of the chosen approach, the size of the clause has a significant impact on the complexity of the problem, and it seems natural to try to keep it to a minimum, which leads us to the following definition.

:::{#def-grimr-simplify}
## Simplification

We say that the clause $(\mathcal{A},\mathcal{B},\mathcal{C},\mathcal{D})$ *simplifies* into the clause $(\mathcal{A}',\mathcal{B}',\mathcal{C}',\mathcal{D}')$ if and only if:

- they induce the same /kmer set, i.e. $\mathcal{I}(\mathcal{A}',\mathcal{B}',\mathcal{C}',\mathcal{D}') = \mathcal{I}(\mathcal{A},\mathcal{B},\mathcal{C},\mathcal{D})$,
- the size of the clause decreases, i.e. $\textrm{size}(\mathcal{A}',\mathcal{B}',\mathcal{C}',\mathcal{D}')\leq \textrm{size}(\mathcal{A},\mathcal{B},\mathcal{C},\mathcal{D})$.
:::

:::{#rem-grimr-natural-language}
Although we expect the majority of clauses to be fairly straightforward, our method is intended to be general and allows for potentially complex clauses. In particular, by manipulating only tags and forgetting, so to speak, the precise references associated with them, it is possible to construct clauses almost in natural language, which we believe is convenient for the user. However, this simplicity of use is also at the root of the clause's becoming possibly unnecessarily complex, and in particular of the possible redundancy of the references among several tags, which motivate the simplification of the clause.
:::

## Simplifying clauses {#sec-grimr-simplify}

In this section, we propose a method for simplifying as much as possible the initial clause $(\mathcal{A},\mathcal{B},\mathcal{C},\mathcal{D})$, with respect to @def-grimr-simplify.

### A straightforward simplification and some reformulations

As a warm-up, consider the following result.

:::{#prp-grimr-union}

Let $P$ and $Q$ be two tags. Then, we have:

- $\operatorname{All}(P)\cap \operatorname{All}(Q)=\operatorname{All}(P\cup Q)$,
- $\operatorname{Any}(P)\cup \operatorname{Any}(Q)=\operatorname{Any}(P\cup Q)$.
:::

:::{.proof}
It follows trivially from the definition of operators $\operatorname{All}$ and $\operatorname{Any}$ -- see @eq-grimr-operator-def.
:::

By denoting $A^\cup  = \bigcup_{A\in \mathcal{A}} A$ and $D^\cup = \bigcup_{D\in\mathcal{D}} D$, we deduce from @prp-grimr-union the following simplification of the clause -- where the decrease in the size of the clause is immediate.

:::{#rem-grimr-collapse}
Note that the sets of sets $\mathcal{A}$ and $\mathcal{D}$ collapse into sets $A^\cup$ and $D^\cup$, that can be seen as single tags. For this reason, $A^\cup$ and $D^\cup$ are denoted with standard font instead of calligraphic.
:::

:::{#cor-grimr-union}

$(\mathcal{A},\mathcal{B},\mathcal{C},\mathcal{D})$ simplifies into $(\lbrace A^\cup \rbrace,\mathcal{B},\mathcal{C},\lbrace D^\cup \rbrace)$.
:::

In the sequel of this section, we shall refer to different reformulations of $\mathcal{I}(\mathcal{A},\mathcal{B},\mathcal{C},\mathcal{D})$, that we introduce here, using @cor-grimr-union:

$$\mathcal{I}(\mathcal{A},\mathcal{B},\mathcal{C},\mathcal{D}) = \left(\operatorname{All}(A^\cup)\cap \left(\bigcap_{B\in\mathcal{B}} \operatorname{Any}(B) \right)\right) \left\backslash \left(\operatorname{Any}(D^\cup) \cup \left(\bigcup_{C\in\mathcal{C}} \operatorname{All}(C)\right) \right)\right.$$ {#eq-grimr-sigma-a}

$$= \bigcap_{B\in \mathcal{B}}\bigcap_{C\in\mathcal{C}} \Big(\big(\operatorname{All}(A^\cup)\cap\operatorname{Any}(B)\big)\setminus\big(\operatorname{Any}(D^\cup) \cup \operatorname{All}(C)\big)\Big)$$ {#eq-grimr-sigma-b}

$$= \bigcap_{B\in \mathcal{B}}\bigcap_{C\in\mathcal{C}} \Big(\big(\operatorname{All}(A^\cup)\setminus \operatorname{All}(C)\big) \cap \big(\operatorname{Any}(B)\setminus\operatorname{Any}(D^\cup)\big)\Big)$$ {#eq-grimr-sigma-c}

$$= \big(\operatorname{All}(A^\cup)\setminus \operatorname{Any}(D^\cup)\big) \cap \big( \dots \big)$$ {#eq-grimr-sigma-d}

where @eq-grimr-sigma-b, @eq-grimr-sigma-c and @eq-grimr-sigma-d are obtained by using standard set identities. In details:

- **@eq-grimr-sigma-b** is obtained from @eq-grimr-sigma-a, using the fact $\left(\bigcap_{i\in I} P_i\right)\setminus \left(\bigcup_{j\in J} Q_j\right) = \bigcap_{\displaystyle\substack{i\in I\\j\in J}} (P_i\setminus Q_j)$ for any arbitrary sets $(P_i)_{i\in I}$ and $(Q_j)_{j\in J}$ where here the $P_i$'s correspond to $\operatorname{All}(A^\cup)\cap \operatorname{Any}(B)$ and the $Q_i$'s to $\operatorname{Any}(D^\cup)\cup \operatorname{All}(C)$;
- **@eq-grimr-sigma-c** is obtained from @eq-grimr-sigma-b, noticing that $(P\cap Q)\setminus (R\cup S) = (Q\setminus R)\cap (P\setminus S)$ for any arbitrary sets $P, Q, R,S$;
- **@eq-grimr-sigma-d** is obtained from @eq-grimr-sigma-a using the same fact as for @eq-grimr-sigma-b, but this time $P_1=\operatorname{All}(A^\cup)$ and $P_2,P_3,\dots$ correspond to the $\operatorname{Any}(B)$'s, and respectively $Q_1=\operatorname{Any}(D^\cup)$ and $Q_2,Q_3,\dots$ correspond to the $\operatorname{All}(C)$'s. Only the first tuple is isolated from the whole intersection, for reasons that will be made clear later.

### Further simplifications

As one may observe from equations @eq-grimr-sigma-a, @eq-grimr-sigma-b, @eq-grimr-sigma-c, @eq-grimr-sigma-d, if we consider the 9 possible "atomic" operations involving $\operatorname{All}$ and/or $\operatorname{Any}$ with the symbols $\cap$, $\cup$ or $\setminus$, 7 of them are present -- the 2 missing ones, $\operatorname{All}(P)\cap \operatorname{All}(Q)$ and $\operatorname{Any}(P)\cup \operatorname{Any}(Q)$, having already been simplified (and thus eliminated) in @prp-grimr-union. Therefore, to simplify clause $\mathcal{I}(\mathcal{A},\mathcal{B},\mathcal{C},\mathcal{D})$ in an optimal way, all we have to do is consider these 7 operations exhaustively, and the minimal necessary conditions under which they can be simplified. By "minimal necessary condition", we mean that it is not possible to simplify an atomic operation without introducing this condition, unless we make conditions on the content of the references -- which we do not want to do in order to preserve the generic aspect of our approach. Therefore, provided two tags $P$ and $Q$, the minimal non-trivial condition we could use is that they share some reference, i.e. $P\cap Q\neq \emptyset$. The next one would be that one tag is included in the other, i.e. without loss of generality that $P\subseteq Q$. We have the following result.

:::{#prp-grimr-simplification}

Provided two tags $P$ and $Q$, the following simplifications can be made:

| | Atomic operation | simplifies into | under minimal necessary condition |
|---|---|---|---|
| (i) | $\operatorname{All}(P)\setminus \operatorname{Any}(Q)$ | $=\emptyset$ | if $P\cap Q \neq \emptyset$ |
| (ii) | $\operatorname{All}(P)\cap \operatorname{Any}(Q)$ | $=\operatorname{All}(P)$ | if $P\cap Q \neq \emptyset$ |
| (iii) | $\operatorname{All}(P)\cup \operatorname{Any}(Q)$ | $=\operatorname{Any}(Q)$ | if $P\cap Q \neq \emptyset$ |
| (iv) | $\operatorname{All}(P)\setminus \operatorname{All}(Q)$ | $=\operatorname{All}(P)\setminus\operatorname{All}(Q^\ast)$ | if $P\cap Q \neq \emptyset$ |
| (v) | $\operatorname{Any}(P)\setminus \operatorname{Any}(Q)$ | $=\operatorname{Any}(P^\ast)\setminus \operatorname{Any}(Q)$ | if $P\cap Q \neq \emptyset$ |
| (vi) | $\operatorname{Any}(P)\cap \operatorname{Any}(Q)$ | $=\operatorname{Any}(P)$ | if $P\subseteq Q$ |
| (vii) | $\operatorname{All}(P)\cup \operatorname{All}(Q)$ | $=\operatorname{All}(P)$ | if $P\subseteq Q$ |

where $P^\ast$ and $Q^\ast$ denote, respectively, $P\setminus(P\cap Q)$ and $Q\setminus (P\cap Q)$.
:::

:::{.proof}
The proof is deferred to @sec-grimr-proof-simplification.
:::

Combining those results with equations @eq-grimr-sigma-a, @eq-grimr-sigma-b, @eq-grimr-sigma-c, @eq-grimr-sigma-d, we get the following result.

:::{#cor-grimr-final}

- **@eq-grimr-sigma-d + @prp-grimr-simplification-(i)**  If $A^\cup \cap D^\cup \neq\emptyset$, then $\mathcal{I}(\mathcal{A},\mathcal{B},\mathcal{C},\mathcal{D})=\emptyset$;
- **@eq-grimr-sigma-b + @prp-grimr-simplification-(ii) and (iii)** we can exclude from the calculation the tags $B\in \mathcal{B}$ such that $B\cap A^\cup \neq \emptyset$, as well as the tags $C\in\mathcal{C}$ such that $C\cap D^\cup \neq \emptyset$;
- **@eq-grimr-sigma-c + @prp-grimr-simplification-(iv) and (v)** we can replace the tags $B\in\mathcal{B}$ by $B\setminus D^\cup$, as well as the tags $C\in\mathcal{C}$ by $C\setminus A^\cup$;
- **@eq-grimr-sigma-a + @prp-grimr-simplification-(vi) and (vii)** we can exclude from $\mathcal{B}$ all tags $B$ such that there exists $B'\in \mathcal{B}$, $B'\subseteq B$, as well as all tags $C$ from $\mathcal{C}$ such that there exists $C'\in\mathcal{C}$, $C'\subseteq C$.
:::

Note that all these operations are simplifications (the decrease in clause size is immediate), and can be performed in any order. However, the order in which we present them is the most appropriate to avoid unnecessary operations: first we check if the clause is empty, then we remove the sets $B$ and $C$ that intersect with $A^\cup$ and $D^\cup$, then perform the required subtractions on the remaining tags, and finish by determining the inclusions within tags, which is the most expensive operation in the list, see below. Note that checking for inclusions also eliminates any duplicates in $\mathcal{B}$ and $\mathcal{C}$.

To identify these inclusions in practice, a straightforward algorithm would be to test for the inclusion of every possible pair of sets, with complexity $O\left(\eta\cdot (|\mathcal{B}^\ast|^2+|\mathcal{C}^\ast|^2)\right)$; where $\eta = \max \left(\displaystyle\max_{B\in\mathcal{B}} |B|,\max_{C\in\mathcal{C}} |C|\right)$ would be the size of the longest tag in either $\mathcal{B}$ or $\mathcal{C}$. It appears to be impossible to beat this worst-case complexity, unless the Strong Exponential Time Hypothesis [@impagliazzo2001complexity] is false^[See for instance this discussion: <https://cstheory.stackexchange.com/q/9897>].

However, in practice it can be useful to partition sets intelligently in order to limit the number of inclusion tests to be performed. With @alg-grimr-remove-inclusions we propose such a method, running in $O(\eta\cdot |\mathcal{P}|^2)$ -- as per the previous discussion -- provided that checking whether $f(n)$ is defined for some $n$ can be done in $O(1)$.

::: {#alg-grimr-remove-inclusions}

```pseudocode
#| html-no-end: true
#| html-indent-lines: true
#| html-line-number: false
#| html-comment-delimiter: "//"
#| pdf-line-number: false
#| pdf-no-end: true
#| pdf-indent-lines: true
#| pdf-italic-comment: true
#| pdf-right-comment: true
#| pdf-comment-color: "darkgray"
#| pdf-comment-delimiter: "//"
#| pdf-placement: "ht!"

\begin{algorithmic}
\Require $\mathcal{P}=\lbrace P_1,P_2,\dots\rbrace$ with $P_i\subseteq \lbrace 1,\dots,N\rbrace$
\Ensure $\mathcal{P}^\star = \lbrace P\in\mathcal{P} : \nexists P'\in\mathcal{P}, P'\subseteq P\rbrace$
\Function{RemoveInclusions}{$\mathcal{P}$}
    \State{Let $f$ be an empty perfect hash table} \Comment{We partition the sets by size.}
    \For{$P\in\mathcal{P}$}
        \If{$f(|P|)$ is not defined}
            \State{Initialize $f(|P|)$ as an empty list}
        \EndIf
        \State{Add $P$ to $f(|P|)$}
    \EndFor
    \State{$\mathcal{P}^\star \gets\emptyset$} \Comment{We now remove unwanted sets.}
    \For{$1\leq n\leq N$ so that $f(n)$ is defined}
        \While{$|f(n)|>0$}
            \State{$P\gets f(n)\text{.pop}()$}
            \For{$n\leq m\leq N$ so that $f(m)$ is defined}
                \For{$P'\in f(m)$}
                    \If{$P\subseteq P'$}
                        \State{Remove $P'$ from $f(m)$}
                    \EndIf
                \EndFor
            \EndFor
            \State{Add $P$ to $\mathcal{P}^\star$}
        \EndWhile
    \EndFor
    \Return $\mathcal{P}^\star$
\EndFunction
\end{algorithmic}
```

RemoveInclusions algorithm.
:::

### Simplification algorithm

Combining the results of @cor-grimr-union and of @cor-grimr-final, we get @alg-grimr-simplification.

::: {#alg-grimr-simplification}

```pseudocode
#| html-no-end: true
#| html-indent-lines: true
#| html-line-number: false
#| html-comment-delimiter: "//"
#| pdf-line-number: false
#| pdf-no-end: true
#| pdf-indent-lines: true
#| pdf-italic-comment: true
#| pdf-right-comment: true
#| pdf-comment-color: "darkgray"
#| pdf-comment-delimiter: "//"
#| pdf-placement: "ht!"

\begin{algorithmic}
\Require $\mathcal{A},\mathcal{B},\mathcal{C},\mathcal{D}$
\Function{ClauseSimplification}{$\mathcal{A},\mathcal{B},\mathcal{C},\mathcal{D}$}
    \State{$A^\cup \gets \bigcup_{A\in\mathcal{A}} A$ and $D^\cup \gets \bigcup_{D\in\mathcal{D}} D$}
    \If{$A^\cup \cap D^\cup \neq \emptyset$}
        \Return $\emptyset,\emptyset,\emptyset,\emptyset$
    \Else
        \State{$\mathcal{B}^\ast \gets \emptyset$}
        \For{$B\in\mathcal{B}$}
            \If{$B\cap A^\cup = \emptyset$}
                \State{Add $B\setminus D^\cup$ to $\mathcal{B}^\ast$}
            \EndIf
        \EndFor
        \State{$\mathcal{B}^\star \gets \Call{RemoveInclusions}{\mathcal{B}^\ast}$}
        \State{$\mathcal{C}^\ast \gets \emptyset$}
        \For{$C\in\mathcal{C}$}
            \If{$C\cap D^\cup = \emptyset$}
                \State{Add $C\setminus A^\cup$ to $\mathcal{C}^\ast$}
            \EndIf
        \EndFor
        \State{$\mathcal{C}^\star \gets \Call{RemoveInclusions}{\mathcal{C}^\ast}$}
        \If{$A^\cup=\emptyset$ and $\mathcal{B}^\star=\emptyset$}
            \State{\textbf{print} "Warning: this clause involves computing the universe"}
        \EndIf
        \Return $\lbrace A^\cup\rbrace ,\mathcal{B}^\star,\mathcal{C}^\star, \lbrace D^\cup\rbrace$
    \EndIf
\EndFunction
\end{algorithmic}
```

ClauseSimplification algorithm.
:::

Note that it is possible to save some time by adding the sets $B'$ in line 9 (respectively $C'$ in line 15) not to $\mathcal{B}^\ast$ (respectively $\mathcal{C}^\ast$) but rather directly to a hash table according to their size (as per lines 2--5 of @alg-grimr-remove-inclusions) before pursuing directly with the search for inclusions (lines 7--14 of @alg-grimr-remove-inclusions). Besides, and although we have not included it for the sake of simplicity, empty sets $B'$ or $C'$ are to be removed. In our implementation, @alg-grimr-simplification is coded in Python, as its complexity relative to the task ahead of us -- computing $\mathcal{I}(\mathcal{A},\mathcal{B},\mathcal{C},\mathcal{D})$ -- is not critical from a performance point of view.

:::{#prp-grimr-simplification-complexity}

@alg-grimr-simplification is correct and returns an optimal simplification of $(\mathcal{A},\mathcal{B},\mathcal{C},\mathcal{D})$ in $O\left(\eta \cdot \big(|\mathcal{B}|^2+|\mathcal{C}|^2\big)+\textrm{size}(\mathcal{A},\mathcal{B},\mathcal{C},\mathcal{D})\right)$, where $\eta=\max \left(\displaystyle\max_{B\in\mathcal{B}} |B|,\max_{C\in\mathcal{C}} |C|\right)$.
:::

:::{.proof}
The correction of the algorithm is immediate by construction by virtue of @cor-grimr-union and @cor-grimr-final, and optimality follows from @prp-grimr-simplification. Computing $A^\cup$ and $D^\cup$ is done in $O(\sum_{A\in\mathcal{A}} |A| + \sum_{D\in\mathcal{D}} |D|)$ -- using a hash table to represent sets, as done in Python with the type `set`.

Checking whether $B\cap A^\cup = \emptyset$ (respectively $C\cap D^\cup = \emptyset$) can be done in $O(|B|)$ (respectively $O(|C|)$), as well as computing $B\setminus D^\cup$ (respectively $C\setminus A^\cup$). Summing over all $B\in\mathcal{B}$ and all $C\in\mathcal{C}$ leads to the result, with the reminder that $\operatorname{RemoveInclusions}(\mathcal{P})$ runs in $O(\eta\cdot|\mathcal{P}|^2)$.
:::

## Computation of $\mathcal{I}(\mathcal{A},\mathcal{B},\mathcal{C},\mathcal{D})$ {#sec-grimr-computation}

After simplifying the clause using @alg-grimr-simplification, we are left to compute the following quantity:
$$\mathcal{I}(\mathcal{A},\mathcal{B},\mathcal{C},\mathcal{D})  = \bigcap_{B\in \mathcal{B}^\star}\bigcap_{C\in\mathcal{C}^\star} \left(\big(\operatorname{All}(A^\cup)\setminus \operatorname{All}(C)\big) \cap \big(\operatorname{Any}(B)\setminus\operatorname{Any}(D^\cup)\big)\right)$$

### General strategy

For each $i\in A^\cup\cup\left( \bigcup_{B\in\mathcal{B}^\star} B\right)\cup \left( \bigcup_{C\in\mathcal{C}^\star} C\right) \cup D^\cup$ -- that is, for each index required at some point in the clause, we must access $\sigma_i$. Two options are available:

- Either the references $R_i$ are stored in a compressed form that does not allow direct access to their set of /kmers, in which case $\sigma_i$ must be constructed as a pre-processing step,
- or the references $R_i$ are already stored in the form of a set of /kmers and all that is needed is to load $\sigma_i$ into memory.

In the sequel, we use the Rust library CBL [@cbl], which implements dynamic sets of /kmers efficiently, using a quotiented representation of /kmers. CBL supports fast insertion/deletion and set operations (union, intersection and difference), including in-place set operations and union/intersection of multiple sets in a single operation.

Our ambition is to restrict the use of RAM as much as possible, in a conservative fashion. To do this, no more than two CBL sets are manipulated in memory at the same time: the set being constructed, and the reference $\sigma_i$ being processed at a given time. However, if one can afford to load several references into memory at once, certain steps described below (using union or intersection) can be performed in batches, thereby speeding up calculation time, thanks to the CBL library.

In addition, we prefer intersection operations (which can be carried out in place, and necessarily reduce the size of sets) over union operations (which involve copies of /kmers and increase the size of sets), whenever possible.

### Initialization

This step has two possible versions, depending on whether $A^\cup = \emptyset$ or not. In both cases, the aim is to construct an initial running set $S$, which will then be reduced in the subsequent construction.

**Case $A^\cup \neq \emptyset$** In this case, we start by constructing the set $\operatorname{All}(A^\cup)$ using the following procedure.

Let $a\in A^\cup$; load into memory $\sigma_a$ -- the initial running set. Then, for each $a'\in A^\cup$, $a'\neq a$, load into memory $\sigma_{a'}$ and intersect it with the current running set. This operation can be performed by batch, if applicable. At the end, we have built the set $S = \operatorname{All}(A^\cup)$.

**Case $A^\cup = \emptyset$** Again, this situation raises two alternatives.

- If $\mathcal{B}^\star \neq \emptyset$. Our initial running set will be one of the sets $\operatorname{Any}(B)$ for some $B\in\mathcal{B}^\star$. It seems only natural to construct the one that requires the fewest operations. Let $B\in\mathcal{B}^\star$ so that $|B|$ is minimal. We have $S=\operatorname{Any}(B) = \bigcup_{b\in B} \sigma_b$. After constructing $S$, we remove $B$ from $\mathcal{B}^\star$.
- Otherwise, $\mathcal{B}^\star = \emptyset$; we have no choice but to build the universe, i.e. $S=\mathcal{U} = \bigcup_{i=1}^N\sigma_i$. Notice that $\mathcal{U}=\operatorname{Any}(\lbrace 1,\dots,N\rbrace)$ -- so we retrieve the previous case with an artificial $B=\lbrace 1,\dots, N\rbrace$.

Either way, the running set is built by iteratively loading into memory each appropriate reference (with or without batches) and taking the union with the previous ones -- in a similar fashion as the computation of $\operatorname{All}(A^\cup)$ indicated above.

### Treating $\mathcal{C}^\star$

Let $S$ be the running set at the end of the previous step. From @eq-grimr-sigma-c, we now compute $\bigcap_{C\in\mathcal{C}^\star} (S\setminus \operatorname{All}(C))$. If $\mathcal{C}^\star = \emptyset$, skip this section. If not, the next procedure is to be followed.

Note that for any sets $P$ and $Q$, $P\setminus Q = P\setminus (Q\cap P)$. Let us fix $C\in\mathcal{C}^\star$. Instead of building $\operatorname{All}(C)$, we build instead $S\cap\operatorname{All}(C)$. Let $S'$ be a copy of $S$ -- $S'$ is our *local* running set, whereas $S$ is the *global* running set. Iteratively, we load into memory $\sigma_c$ for each $c\in C$, and intersect it against the local running set. This part can be done with batches. At the end, the local running set is $S'=S\cap\operatorname{All}(C)$, and we replace $S$ -- the global running set -- by $S\setminus S'$. We repeat this whole process for each remaining $C'\in\mathcal{C}^\star$, $C'\neq C$.

### Treating $D^\cup$

Let $S$ be the running set at the end of the previous steps. We rewrite @eq-grimr-sigma-c, as:

$$\mathcal{I}(\mathcal{A},\mathcal{B},\mathcal{C},\mathcal{D}) = S\cap \left( \bigcap_{B\in \mathcal{B}^\star} \big(\operatorname{Any}(B)\setminus\operatorname{Any}(D^\cup)\big)\right)
    = \left(\bigcap_{B\in\mathcal{B}^\star} \operatorname{Any}(B)\right) \cap (S\setminus \operatorname{Any}(D^\cup))$$ {#eq-grimr-sigma-simpl}

We are interested here in the term $S\setminus \operatorname{Any}(D^\cup)$; we have
$$S\setminus \operatorname{Any}(D^\cup) = S\left\backslash \left(\bigcup_{d\in D^\cup} \sigma_d\right)\right. = \bigcap_{d\in D^\cup} (S\setminus \sigma_d).$$

Noticing that $(P\setminus Q) \cap (P\setminus R) = (P\setminus Q) \setminus R$, for any sets $P, Q$ and $R$, we can compute $S\setminus\operatorname{Any}(D^\cup)$ by successively replacing $S$ by $S\setminus \sigma_d$ for each $d\in D^\cup$.

Obviously, if $D^\cup=\emptyset$, this step is skipped.

### Treating $\mathcal{B}^\star$

Let $S$ be the running set at the end of the previous steps. If $\mathcal{B}^\star=\emptyset$, skip this step. Otherwise, from @eq-grimr-sigma-simpl, we are left with:
$$\mathcal{I}(\mathcal{A},\mathcal{B},\mathcal{C},\mathcal{D})  = S \cap\left(\bigcap_{B\in\mathcal{B}^\star} \operatorname{Any}(B)\right) = \bigcap_{B\in\mathcal{B}^\star} \big(S\cap \operatorname{Any}(B)\big);$$
that can be sequentially computed as $\left(\big((S\cap \operatorname{Any}(B_1)) \cap \operatorname{Any}(B_2)\big) \cap \dots \right)$. Notice that
$$S\cap \operatorname{Any}(B) = \bigcup_{b\in B} \big(S\cap \sigma_b\big).$$

There is no escaping the calculation of a union here; we are again using a local running set $S'$ for this task. Let us fix some $B\in\mathcal{B}^\star$ and initialize the local set $S'$ as an empty set. For each reference $b\in B$, we compute $S\cap \sigma_b$ -- notice that $S$, the global set, must not be modified here -- and take the union of this set with $S'$. At the end of this process, replace $S$ by $S'$ and repeat for each remaining $B'\in\mathcal{B}^\star$, $B'\neq B$.

:::{#rem-grimr-local-set}
Note that we adopt this procedure, rather than simply calculating $S\cap \operatorname{Any}(B)$ directly, in order to limit the size of the sets manipulated. This is because the set $\operatorname{Any}(B)$ can be potentially much larger than $S$, while the set $S\cap \sigma_b$ is necessarily contained in $S$.
:::

After dealing with $\mathcal{B}^\star$, the set $S$ is exactly equal to $\mathcal{I}(\mathcal{A},\mathcal{B},\mathcal{C},\mathcal{D})$.

### Algorithm

@alg-grimr-construction sums up the procedure of this section. As a reminder, lower case letters (e.g. $b$) designate indices of *references*; capital letters (e.g. $B$) designate sets of *indices*; calligraphic letters (e.g. $\mathcal{B}$) designate sets of *sets of indices*. $S_l$ designates the *local* running set -- specific to the current step -- whereas $S_g$ designates the *global* running set, i.e. the solution set under construction.

::: {#alg-grimr-construction}

```pseudocode
#| html-no-end: true
#| html-indent-lines: true
#| html-line-number: false
#| html-comment-delimiter: "//"
#| pdf-line-number: false
#| pdf-no-end: true
#| pdf-indent-lines: true
#| pdf-italic-comment: true
#| pdf-right-comment: true
#| pdf-comment-color: "darkgray"
#| pdf-comment-delimiter: "//"
#| pdf-placement: "ht!"

\begin{algorithmic}
\Require $A^\cup,\mathcal{B}^\star,\mathcal{C}^\star,D^\cup$
\Function{ClauseComputation}{$A^\cup,\mathcal{B}^\star,\mathcal{C}^\star,D^\cup$}
    \If{$A^\cup = \emptyset$}
        \If{$\mathcal{B}^\star=\emptyset$}
            \State{Let $B=\lbrace 1,\dots,N\rbrace$}
        \Else
            \State{Let $B\in\mathcal{B}^\star$ so that $|B|$ is minimal}
            \State{Remove $B$ from $\mathcal{B}^\star$}
        \EndIf
        \State{$S_l\gets \emptyset$}
        \For{$b\in B$}
            \State{Load into memory $\sigma_b$}
            \State{$S_l\gets S_l\cup \sigma_b$}
        \EndFor
    \Else
        \State{Let $a\in A^\cup$}
        \State{Load into memory $\sigma_a$}
        \State{$S_l \gets \text{Copy}(\sigma_a)$}
        \For{$a'\in A^\cup,\ a'\neq a$}
            \State{Load into memory $\sigma_{a'}$}
            \State{$S_l \gets S_l\cap \sigma_{a'}$}
        \EndFor
    \EndIf
    \State{$S_g\gets S_l$}
    \For{$C\in\mathcal{C}^\star$}
        \State{$S_l\gets \text{Copy}(S_g)$}
        \For{$c\in C$}
            \State{Load into memory $\sigma_c$}
            \State{$S_l\gets S_l\cap \sigma_c$}
        \EndFor
        \State{$S_g\gets S_g\setminus S_l$}
    \EndFor
    \For{$d\in D^\cup$}
        \State{Load into memory $\sigma_d$}
        \State{$S_g\gets S_g\setminus \sigma_d$}
    \EndFor
    \For{$B\in\mathcal{B}^\star$}
        \State{$S_l\gets \emptyset$}
        \For{$b\in B$}
            \State{Load into memory $\sigma_b$}
            \State{$S_l\gets S_l \cup (S_g\cap \sigma_b)$} \Comment{$S_g$ must not be modified}
        \EndFor
        \State{$S_g\gets S_l$}
    \EndFor
    \Return $S_g$
\EndFunction
\end{algorithmic}
```

ClauseComputation algorithm.
:::

In order to analyse the complexity of @alg-grimr-construction, we make the following assumptions.

(i) We assume that the references are all of the same size, which we denote $K$ -- so that, $\forall i$, $K=|\sigma_i|$. We assume that a reference is loaded into memory in $O(K)$ time;
(ii) for any two /kmer sets $P$ and $Q$, we assume that computing $P\cap Q$ can be done in $O(\min(|P|,|Q|))$; that computing $P\setminus Q$ can be done in $O(|P|)$; and that computing $P\gets P\cup Q$ -- i.e., extending $P$ with the content of $Q$ -- can be done in $O(|Q|)$.

:::{#rem-grimr-cbl-simplification}
The complexities presented in (ii) are simplifications of the actual complexities of the operations as implemented in the CBL library. The interested reader can find their detailed complexity in @sec-grimr-cbl-complexity.
:::

:::{#prp-grimr-construction-complexity}

@alg-grimr-construction admits the following complexities:

| Case | $A^\cup \neq \emptyset$ | $A^\cup = \emptyset$ and $\mathcal{B}^\star \neq \emptyset$ | $A^\cup = \mathcal{B}^\star = \emptyset$ |
|---|---|---|---|
| Time | $O\big(K\cdot \textrm{size}(\mathcal{A},\mathcal{B},\mathcal{C},\mathcal{D})\big)$ | $O\big(K\cdot \textrm{size}(\mathcal{A},\mathcal{B},\mathcal{C},\mathcal{D})\big)$ | $O\big(K\cdot (N+\textrm{size}(\mathcal{A},\mathcal{B},\mathcal{C},\mathcal{D}))\big)$ |
| Space | $O(K)$ | $O(K\cdot \lvert B\rvert)$ for $B\in\mathcal{B}^\star$ with $\lvert B\rvert$ minimal | $O(K\cdot N)$ |

where $\textrm{size}(\mathcal{A},\mathcal{B},\mathcal{C},\mathcal{D})$ is defined in @eq-grimr-size.
:::

:::{.proof}
The proof can be found in @sec-grimr-proof-construction.
:::

Remember that in terms of space, our approach is conservative; if one can afford to have several references loaded in memory, one can perform the unions or intersections in batches, which are faster in practice with the CBL library, as already stated earlier.

It is also clear that @sec-grimr-simplify, designed to simplify the clause, is of great interest in view of the time complexity of @alg-grimr-construction.

## Implementation

The implementation of our solution is composed of two main parts, a clause builder in Python, and a wrapper for the CBL software written in Rust.
CBL is a dynamic set structure for /kmers. The clause builder reworks the initial clause to minimize the number of operations and of files to load.
The wrapper deals with fasta I/Os and executes @alg-grimr-construction according to the clause refined by the clause builder (implementing @alg-grimr-simplification). It benefits from recent advancements in CBL allowing set operations on multiple entries (batch).
We provide a batch parameter $b$ controlling the number of CBL sets loaded at the same time.
This parameter is equal to 1 by default to limit memory usage.
Choosing a larger $b$ accelerates the computation of unions and intersections (since CBL can process $b$ sets simultaneously) but increases peak memory usage.

Our implementation can be found at <https://github.com/kamimrcht/Grimr>.

## Results

In the following, we test the most time consuming operations in the pipeline: set operations used in @alg-grimr-construction. CBL allows to perform these operations in batches of size $X$,
which means that it will apply a set operation simultaneously on $X$ datasets. We evaluate the benefits of an increasing batch size in @sec-grimr-res-batch.
We then show examples of our tool's usage in @sec-grimr-res-illus.
All experiments were performed on a single cluster node running with Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz with 128GB of RAM and Ubuntu 22.04.

### Batch size strategy for set operations {#sec-grimr-res-batch}

We analyse the execution time and /kmer processing rates at various batch sizes. This analysis aims to understand how batch processing impacts the performance of these operations on large genomic datasets.
For each operation, we varied the batch size from 1 to 20 on 1000 bacterial Refseq genomes (1.7 billion of distinct /kmers) to assess the impact on performance (accessions in @tbl-grimr-accessions).

We recorded the time taken for each batch size and calculated the /kmer processing rates. As depicted in @fig-grimr-res (top), all operations show a decreasing trend in execution time as the batch size increases. The input and output /kmers per second increase with batch size, indicating improved efficiency with larger batches. The peak RAM during those operations was 103 GB, when unioning all datasets. It is noteworthy that such an amount is not a reflection of most clauses, and can in practice be an order of magnitude lower at least (an example is provided in @sec-grimr-res-illus on a similar amount of /kmers).

We also inspected speedup and efficiency of the batch strategy. Speedup is defined as the ratio $\frac{\textrm{time~for~batch~size}~1}{\textrm{time~for~batch~size}~N}$ and efficiency as the ratio $\frac{\textrm{batch~size}}{\textrm{speedup}}$. Here we report results for the union and observe similar behaviours for the other operations. @fig-grimr-res (bottom left) shows that the speedup increases as the batch size increases, indicating that larger batch sizes reduce the time required for processing. However, the efficiency decreases as the batch size increases, suggesting that the gains have a diminishing return with larger batch sizes.

<!-- TODO: missing figure fig-grimr-res (PNG: benchmark_time_vs_batch_size_17G_kmers_plot2.png, union_speedup_efficiency_vs_batch_size_bact_plot.png, union_efficiency_vs_batch_size_bact_kmers_plot.png) -->

We also looked at the impact of batch effect's scalability with an increasing number of /kmers using collections of 10, 100 and 1000 datasets (33 million, 257 million and 1.7 billion of distinct /kmers respectively).
We focused on the union as it is our most costly operation. @fig-grimr-res (bottom right) shows that the largest (1.7G and 257M) /kmer dataset generally shows better efficiency compared to the 33M /kmer dataset, particularly at higher batch sizes.

In order to assess similar results on different types of data, we produced similar experiments on RNA-seq human samples. For each operation, we varied the batch size from 1 to 20 on 200 human RNA-seq samples, up to 700 million of /kmers. The results present similar trends and are presented in @fig-grimr-supp-res.

<!-- TODO: missing figure fig-grimr-supp-res (PNG: benchmark_time_vs_batch_size_700M_kmers_plot2.png, union_speedup_efficiency_vs_batch_size_700M_kmers_plot.png, union_efficiency_vs_batch_size_9M_24M_700M_kmers_plot.png) -->

### Application cases {#sec-grimr-res-illus}

In the following, we tested the full piece of software in order to obtain subsets of /kmers relative to a clause. We illustrate the clause types in @fig-grimr-res-illus (a). We report the resources used for the runs, and illustrate excerpts of the results.

**Find plasmid /kmers in bacterial genomes.**
We indexed the whole plasmid database (PLSDB [@schmartz2022plsdb]), as well as ten *Salmonella* genomes (accessions in @tbl-grimr-accessions) in 1h15 min.
We then queried 21-mers present at the intersection of the PLSDB with any of the genomes. The operation took 5 minutes and yielded 149,180 /kmers out of the 1.7 billion /kmers of PLSDB (75G of RAM).

<!-- TODO: missing figure fig-grimr-res-illus (PNG: illustration.png) -->

**Find /kmers unique to an experiment.**
We indexed several RNA-seq short reads datasets associated with putative oncogenes, including a *fusion_dataset* known for containing transcript fusion events (accessions in @tbl-grimr-accessions), representing 74.5 million /kmers, in 5 minutes (3GB RAM).
We queried the 21-mers exclusive to *fusion_dataset* in 51 seconds. We then assembled these /kmers using `bcalm2` [@bcalm2] (options: `-kmer-size 21 -abundance-min 2`), yielding $\approx$ 1.5 million of contigs, among which we obtained 134 contigs larger than 1,000 nucleotides. Manual exploration showed that /kmers from the results indeed displayed different aberrant splicing patterns, we show two examples in @fig-grimr-res-illus (b) and (c), illustrating the capacity of our method to identify /kmers of interest.

## Conclusion

In this chapter, we presented a framework for the efficient enumeration of /kmers within a dataset that satisfy certain constraints on their metadata tags. Firstly, we proposed a user-friendly way of constructing clauses, close to natural language, by freely associating tags with operations ($\operatorname{All}$, $\operatorname{Any}$, $\operatorname{NotAll}$ and $\operatorname{NotAny}$). This clause is then simplified in order to reduce computing delays. Secondly, the solution set of the clause is constructed using CBL, a Rust library dedicated to optimised computation of set operations involving /kmers. Particular care has been taken to ensure that this construction is parsimonious both in terms of memory and computing time, in particular by operating in place whenever possible, in order to reduce unnecessary copies. An option is provided for batch processing of the data, should memory not be a limiting factor.

Our results demonstrate that larger batch sizes and datasets enhance performance and scalability, with unions up to 1.7 billion /kmers being feasible on a single cluster node. Practical applications, such as identifying plasmid /kmers in bacterial genomes and isolating unique /kmers in RNA-seq datasets, highlight the tool's utility in genomic research.

This work allows a new type of query on genomic indexes, which we hope will lead to the discovery of new /kmers relevant to understanding biological phenomena, such as in the medical field where certain diagnoses rely on the detection of known patterns in the genome -- and where the discovery of new patterns is therefore of utmost interest, as those that populate molecular signature databases [@liberzon2011molecular].

Indexes capable of taking abundance into account are an ongoing major challenge, which has seen significant contributions in recent years, see for example [@reindeer; @metagraph; @needle]. The method we propose in this chapter is based solely on the presence/absence of /kmers; an interesting prospect for future work would be to take into account abundances -- i.e. the number of times a /kmer appears in a reference -- to allow an even wider range of clauses.

## Supplementary material

### Accessions

In addition to @tbl-grimr-accessions, the full lists of accessions for the benchmark on 1000 bacterial genomes, as well as for the benchmark on 200 human RNA-seq, can be found at <https://github.com/kamimrcht/Grimr/blob/main/accessions.txt>.

| Species | Type | Bank | Accessions |
|---|---|---|---|
| *Salmonella enterica* | Genome | GenBank | GCA_011232695.1_PDT000673809.1_genomic.fna.gz |
| | | | GCA_015098575.1_PDT000855768.1_genomic.fna.gz |
| | | | GCA_007565205.1_PDT000297230.2_genomic.fna.gz |
| | | | GCA_015034225.1_PDT000869352.1_genomic.fna.gz |
| | | | GCA_005401825.1_PDT000491193.1_genomic.fna.gz |
| | | | GCA_021279925.1_PDT001211007.1_genomic.fna.gz |
| | | | GCA_011288685.1_PDT000626723.1_genomic.fna.gz |
| | | | GCA_022434075.1_PDT001256364.1_genomic.fna.gz |
| | | | GCA_008929265.1_PDT000602336.1_genomic.fna.gz |
| | | | GCA_017486225.1_PDT000985998.1_genomic.fna.gz |
| Human | Reads RNA-seq | SRA | SRR8615240 |
| | | | SRR8615242 |
| | | | SRR8616107 |

: Summary of Accessions from GenBank and SRA for application cases. {#tbl-grimr-accessions}

### Proof of @prp-grimr-simplification {#sec-grimr-proof-simplification}

The idea of the proof is identical for the 7 cases to be dealt with: we express the atomic operation in terms of references, using the usual set identities to highlight elements that could be simplified provided that certain minimum necessary conditions are met. Recall also that the conditions must be on tags $P$ and $Q$, not on the references. Therefore, the minimal non-trivial condition is that $P\cap Q\neq \emptyset$; the next one is that $P\subseteq Q$.

**Proof of (i), (ii) and (iii)** First, observe that we can express the first 3 atomic operators in terms of references in the following manners (using standard set identities).
$$\begin{aligned}
 \operatorname{All}(P)\setminus \operatorname{Any}(Q) &= \bigcap_{\substack{i\in P\\ j\in Q}}( \sigma_i\setminus \sigma_j)\\
 \operatorname{All}(P)\cap \operatorname{Any}(Q) & = \bigcap_{i\in P} \left(\bigcup_{j\in Q} (\sigma_i\cap\sigma_j)\right) = \bigcup_{j\in Q} \left( \bigcap_{i\in P}(\sigma_j \cap \sigma_i)\right)\\
\operatorname{All}(P)\cup \operatorname{Any}(Q) &= \bigcap_{i\in P} \left( \bigcup_{j\in Q} (\sigma_i \cup\sigma_j)\right) = \bigcup_{j\in Q} \left(\bigcap_{i\in P}(\sigma_j \cup \sigma_i)\right)
\end{aligned}$$
It is not difficult to see that these expressions cannot be simplified without making assumptions about the content of $\sigma_i,\sigma_j$: in order to simplify without such recourse, we must admit the first minimal condition, i.e. that $P\cap Q\neq \emptyset$.

Under this assumption, the rest of the proof follows immediately: let $x\in \operatorname{All}(P)$. Then $\forall i\in P$, $x\in \sigma_i$. In particular, for any $j\in P\cap Q$, $x\in \sigma_j$. Since $j\in Q$, $x\in \operatorname{Any}(Q)$. Therefore, $\operatorname{All}(P) \subseteq \operatorname{Any}(Q)$. For any two sets $A$ and $B$, we have $A\subseteq B \iff A\cup B= B\iff A\cap B = A \iff A\setminus B=\emptyset$.

**Proof of (iv) and (v)** Observe that
$$\begin{aligned}
\operatorname{All}(P)\setminus \operatorname{All}(Q) &= \bigcap_{i\in P}\left(\bigcup_{j\in Q} (\sigma_i\setminus \sigma_j)\right)= \bigcup_{j\in Q}\left(\bigcap_{i\in P}(\sigma_i\setminus \sigma_j)\right)\\
\operatorname{Any}(P)\setminus \operatorname{Any}(Q) &= \bigcup_{i\in P}\left(\bigcap_{j\in Q} (\sigma_i\setminus \sigma_j)\right)= \bigcap_{j\in Q}\left(\bigcup_{i\in P}(\sigma_i\setminus \sigma_j)\right)
\end{aligned}$$
Once again, it is not possible to simplify any of these formulas without any assumption on $\sigma_i,\sigma_j$. However, if we suppose that $P\cap Q\neq \emptyset$, we can simplify things since $\emptyset$ appears anytime we have some $i\in P=j\in Q$. Let us denote $P^\ast = P\setminus (P\cap Q)$ and $Q^\ast = Q\setminus (P\cap Q)$.

For (iv), $\operatorname{All}(P)\setminus\operatorname{All}(Q)$, considering the right-hand formula, we have $\bigcap_{i\in P} (\sigma_i\setminus\sigma_j) =\emptyset$ for any $j\in P\cap Q$. Therefore,
$$\operatorname{All}(P)\setminus\operatorname{All}(Q)= \bigcup_{j\in Q}\left(\bigcap_{i\in P}(\sigma_i\setminus \sigma_j)\right)= \bigcup_{j\in Q^\ast}\left(\bigcap_{i\in P}(\sigma_i\setminus \sigma_j)\right)=\operatorname{All}(P)\setminus\operatorname{All}(Q^\ast),$$
as claimed. For (v), to get $\operatorname{Any}(P)\setminus \operatorname{Any}(Q) = \operatorname{Any}(P^\ast)\setminus \operatorname{Any}(Q)$, we use a similar proof, this time using the left-hand formula.

**Proof of (vi) and (vii)** Observe that
$$\operatorname{Any}(P)\cap \operatorname{Any}(Q)= \bigcup_{\substack{i\in P\\ j\in Q}} (\sigma_i\cap \sigma_j) \quad\text{and}\quad
    \operatorname{All}(P)\cup \operatorname{All}(Q)= \bigcap_{\substack{i\in P\\ j\in Q}} (\sigma_i\cup \sigma_j)$$
As before, in order to simplify, we start by assuming that $P\cap Q\neq \emptyset$. Denoting again $P^\ast = P\setminus (P\cap Q)$ and $Q^\ast = Q\setminus (P\cap Q)$, and noticing for (vi) that $(A\cup B)\cap (A\cup C) = A \cup (B\cap C)$ and for (vii) that $(A\cap B)\cup(A\cap C) = A\cap (B\cup C)$, we can extract each $\sigma_k$ such that $k\in P\cap Q$, and obtain
$$\begin{aligned}
\operatorname{Any}(P)\cap \operatorname{Any}(Q) &=  \left(\bigcup_{k\in P\cap Q} \sigma_k \right) \cup \left(\bigcup_{\substack{i\in P^\ast\\ j\in Q^\ast}} (\sigma_i\cap \sigma_j)\right) = \operatorname{Any}(P\cap Q) \cup \big(\operatorname{Any}(P^\ast) \cap \operatorname{Any}(Q^\ast)\big)\\
\operatorname{All}(P)\cup \operatorname{All}(Q) &=  \left(\bigcap_{k\in P\cap Q} \sigma_k \right) \cap \left(\bigcap_{\substack{i\in P^\ast\\ j\in Q^\ast}} (\sigma_i\cup \sigma_j)\right) = \operatorname{All}(P\cap Q) \cap \big(\operatorname{All}(P^\ast) \cup \operatorname{All}(Q^\ast)\big)
\end{aligned}$$
Despite $|P\cap Q| + |P^\ast| + |Q^\ast| \leq |P| + |Q|$, there is no guarantee that this manipulation will simplify the final clause with respect to @def-grimr-simplify. The atomic operations $\operatorname{Any}(P)\cap \operatorname{Any}(Q)$ and $\operatorname{All}(P)\cup \operatorname{All}(Q)$ typically appear in the context of calculating $\bigcap_{B\in\mathcal{B}}\operatorname{Any}(B)$ and $\bigcup_{C\in\mathcal{C}} \operatorname{All}(C)$ -- see @eq-grimr-sigma-a. The introduction of the symbol $\cup$ in (vi), and the symbol $\cap$ in (vii), breaks the standard form of the clause (i.e. an intersection of operators among $\operatorname{All}$, $\operatorname{Any}$, $\operatorname{NotAll}$ and $\operatorname{NotAny}$). We could distribute to create as many new standard clauses, but at the cost of repeating identical tags in each clause. In other words, on the scale of the entire query, we are not simplifying at all.
Consider for instance, the very simple clause $\mathcal{I}=\operatorname{All}(R) \cap \operatorname{Any}(P) \cap \operatorname{Any}(Q)$, with $P\cap Q\neq \emptyset$, and such that $P\cap R = Q\cap R = \emptyset$ (so that $\operatorname{All}(R)\cap \operatorname{Any}(\cdot)$ does not get simplified by virtue of (ii)). Then, by what precedes, we have:
$$\begin{aligned}
\mathcal{I} &=\operatorname{All}(R) \cap \Big[\operatorname{Any}(P\cap Q) \cup \big(\operatorname{Any}(P^\ast) \cap \operatorname{Any}(Q^\ast)\big)\Big]\\
&= \Big[\operatorname{All}(R)\cap\operatorname{Any}(P\cap Q)  \Big] \cup \Big[\operatorname{All}(R) \cap \operatorname{Any}(P^\ast) \cap \operatorname{Any}(Q^\ast) \Big]
\end{aligned}$$
which is now 2 clauses in standard form. If each clause is indeed of size less than $\text{size}(\mathcal{I})$, globally, the total size of all clauses might have increased, depending on whether
$$2\cdot|R| + |P\cap Q| + |P^\ast| + |Q^\ast| > |R| + |P| + |Q|$$
or not, i.e. whether $|R|> |P\cap Q|$ or not. Therefore, the condition $P\cap Q\neq\emptyset$ is not enough, in this context, to ensure the simplification of the clause. We shall consider the next minimal condition, that is, $P\subseteq Q$.

To conclude the proof, with $P\subseteq Q$, (vi) it suffices to note that $\operatorname{Any}(Q) = \big(\operatorname{Any}(P) \cup \operatorname{Any}(Q^\ast)\big) \supseteq \operatorname{Any}(P)$ -- hence, intersected against $\operatorname{Any}(P)$, we obtain $\operatorname{Any}(P)$. (vii) Similarly, $\operatorname{All}(Q) = \big(\operatorname{All}(P)\cap\operatorname{All}(Q^\ast)\big)\subseteq \operatorname{All}(P)$ -- so that, united with $\operatorname{All}(P)$, we obtain $\operatorname{All}(P)$.

### Simplified complexity model for CBL {#sec-grimr-cbl-complexity}

Internally, CBL represents /kmers as their smallest cyclic rotations, also known as necklaces, and stores them in a quotiented data structure: if two /kmers share the same necklace prefix of size $p$, this prefix is written only once and the suffixes are grouped together in a bucket. The full description of this construction can be found in [@cbl].

Provided a CBL set $A$, we denote its set of necklace prefixes as $P_A$. Provided with a prefix $p \in P_A$, we denote by $A_p$ the set of /kmers of $A$ whose necklace starts with $p$.

Every set operation between two sets $A$ and $B$ relies on first comparing $P_A$ to $P_B$ and then comparing the suffix buckets corresponding to prefixes in $P_A \cap P_B$. Thus, the complexity of any set operation is lower bounded by $|P_A| + |P_B|$.

Fortunately, since the necklace transformation preserves locality, $|P_A|$ is very small compared to $|A|$, usually 1-10% of $|A|$. What's more, the prefixes are stored in a bitvector, so we can compare them very quickly, 64 comparisons at once.

To simplify our calculations, we assume that each bucket can be copied in constant time.

**Union in place**

When the union is done in place, i.e. $A \gets A \cup B$, we only need to iterate over the /kmers of $B$, which lowers the complexity:

- for each $p \in P_A \cap P_B$, we update $A_p \gets A_p \cup B_p$ in $O(|B_p|)$.
- for each $p \in P_B \setminus P_A$, $B_p$ is copied in $O(1)$.

This gives a total complexity of $$O \left( |P_B| + \sum_{p \in P_A \cap P_B}|B_p| \right)$$ which is upper bounded by $O(|B|)$.

**Intersection**

The intersection of $A$ and $B$ is computed as follows:

- for each $p \in P_A \cap P_B$, we compute $A_p \cap B_p$ in $O(\min(|A_p|, |B_p|))$.
- for each $p \in P_A \Delta P_B$, the corresponding bucket is discarded.

This gives a total complexity of $$O \left( |P_A| + |P_B| + \sum_{p \in P_A \cap P_B} \min(|A_p|, |B_p|) \right)$$ which is upper bounded by $O(\min(|A|, |B|) + \max(|P_A|, |P_B|))$.

**Difference**

The difference of $A$ and $B$ is computed as follows:

- for each $p \in P_A \cap P_B$, we compute $A_p \setminus B_p$ in $O(|A_p|)$.
- for each $p \in P_A \setminus P_B$, the corresponding bucket is copied in $O(1)$.
- for each $p \in P_B \setminus P_A$, the corresponding bucket is discarded.

This gives a total complexity of $$O \left( |P_A| + |P_B| + \sum_{p \in P_A \cap P_B} |A_p| \right)$$ which is upper bounded by $O(|A| + |P_B|)$.

:::{#rem-grimr-complexity-assumptions}
For the proof of @prp-grimr-construction-complexity (see next section), we made the assumptions that $A\cap B$ can be computed in $O(\min(|A|,|B|))$; $A\setminus B$ in $O(|A|)$; and $A\gets A\cup B$ in $O(|B|)$. As can be seen, these assumptions ignore the cost associated to prefixes -- which are negligible in practice.
:::

### Proof of @prp-grimr-construction-complexity {#sec-grimr-proof-construction}

Complexities are analysed separately.

**Space complexity** References require $O(K)$ of space, and only one of them is loaded into memory at any given time. In addition, the solution set we construct is gradually reduced over the course of the algorithm, and is therefore maximal at initialisation -- hence the result, depending on the case.

**Time complexity** We start by analysing the conditional block from lines 1 to 17.

- If $A^\cup\neq\emptyset$, $S_l$ is built in $O(K)$. Then, for each $a' \in A^\cup$, $a'\neq a$, computing $S_l\cap \sigma_{a'}$ takes, as per assumption (ii), $O(\min(|S_l|,|\sigma_{a'}|))$, which is $O(K)$. Summing over all $a'$ and taking into account $a$ leads to a complexity of $O(K\cdot|A^\cup|)$;
- if $A^\cup=\emptyset$ and $\mathcal{B}^\star\neq \emptyset$, assuming that accessing $|B|$ can be done in $O(1)$, finding the smallest set $B\in\mathcal{B}^\star$ is done in $O(|\mathcal{B}^\star|)$. By assumption (ii), building $S_l$ in lines 8--10 is done in $O(K\cdot|B|)$;
- if $A^\cup=\mathcal{B}^\star = \emptyset$, building $S_l$ in lines 8--10 is done in $O(K\cdot N)$ by assumption (iii).

For lines 19--24, assuming $\mathcal{C}^\star\neq\emptyset$; let us fix $C\in\mathcal{C}^\star$. Building $S_l$ in line 20 is $O(K)$; the loop of lines 21--23 is $O(K\cdot |C|)$ -- as per assumption (ii). Line 24 is $O(|S_g|)$, which is bounded by $O(K)$. Therefore, summing over all $C\in\mathcal{C}^\star$, we get $O\left(K\cdot \left(|\mathcal{C}^\star|+\sum_{C\in\mathcal{C}^\star} |C|\right)\right)$, which can be simplified to $O\left(K\cdot\sum_{C\in\mathcal{C}^\star} |C|\right)$.

Lines 25--27 are in $O(K\cdot |D^\cup|)$, again since $|S_g|\leq K$ and with assumption (ii).

Finally, for lines 28--33, let us fix $B\in\mathcal{B}^\star$. At line 32, computing $S_g\cap \sigma_b$ is $O(\min(|S_g|,|\sigma_b|))$ which is $O(K)$; since $|S_g \cap \sigma_b| \leq K$, computing $S_l\cup(S_g\cap \sigma_b)$ is also $O(K)$. Summing over all $B\in\mathcal{B}^\star$ leads to $O\left(K\cdot \sum_{B\in\mathcal{B}^\star} |B|\right)$. Note that if one set $B$ was removed from $\mathcal{B}^\star$ at the initialisation (in the case $A^\cup=\emptyset$ and $\mathcal{B}^\star\neq\emptyset$), summing the complexity of initialisation with the complexity of lines 28--33 does indeed lead to the same complexity, i.e. $O\left(K\cdot \sum_{B\in\mathcal{B}^\star} |B|\right)$.

In the end, combining all the intermediate complexities leads to the result.
