# Vectorized computation of minimizers

:::{.callout-note}
This chapter is adapted from [@simd-minimizers].
:::

In this chapter, we focus on computing *random minimizers* as efficiently as possible:
for each window of *w* consecutive /kmers, we select the smallest /kmer given a pseudo-random order (see @sec-intro-minimizers for a detailed introduction).
This order is usually given by comparing hash values, and in case of ties the leftmost smallest /kmer is selected.
In particular, we are interested finding the *positions* of random minimizers in a sequence, from which we can extract the minimizers themselves.
We first focus on computing *forward* minimizers (without taking reverse-complement into account) for simplicity, and then describe a solution for *canonical* minimizers in @sec-canonical-minimizers.

## Existing algorithms for random minimizers

Assuming that we can easily iterate over /kmer hashes, for instance using a rolling hash as described in @sec-rolling-hash, our problem becomes a *sliding window minimum*.
Given a sliding window of *w* values (in our case /kmer hashes), we want to output the position of the the smallest value (breaking ties with the leftmost one).
Many approaches can be used to solve this problem, in this section we will focus on three common ones: the "naive" algorithm, the "rescan" algorithm and the monotone queue algorithm.
A summarized comparison of these three algorithms is given in @tbl-algos-sliding-min.

### Naive approach

The simplest approach is to simply loop over the $w$ values in each window independently, as described in @alg-sliding-min-naive.
This takes $O(wn)$ time, but has the benefit of being branchless and can still be quite efficient when $w$ is small by using vectorized instructions.

::: {#alg-sliding-min-naive}

```pseudocode
#| html-no-end: true
#| html-indent-lines: true
#| html-line-number: false
#| html-comment-delimiter: "//"
#| pdf-line-number: false
#| pdf-no-end: true
#| pdf-indent-lines: true
#| pdf-italic-comment: true
#| pdf-right-comment: true
#| pdf-comment-color: "darkgray"
#| pdf-comment-delimiter: "//"
#| pdf-placement: "ht!"

\begin{algorithmic}
\Function{Naive}{$w, \texttt{vals}$}
    \For{$i$ in $\{0, \ldots, |\texttt{vals}| - w\}$}
        \State{\textbf{yield} $\arg \min \{\texttt{vals}[i], \ldots, \texttt{vals}[i+w-1]\}$}
    \EndFor
\EndFunction
\end{algorithmic}
```

Naive algorithm for sliding window minimum
:::

### Monotone queue

A solution with better complexity, detailed in @alg-sliding-min-queue, is to use a *monotone queue*, which stores a non-decreasing subsequence of the $w$ hashes, alongside their positions.
For instance, this is the method used in Bifrost [@bifrost].
Every time the window slides one to the right and we are about to push a new /kmer hash onto the right of the queue, we first
remove any values larger than it, as they are "shadowed" by the new hash and can never be minimal anymore.
The minimum of the window is then always the leftmost queue element.
This data structure guarantees an amortized constant time update, but has many unpredictable branches due to removing between $0$ and $w$ values, which makes it costly in practice.

::: {#alg-sliding-min-queue}

```pseudocode
#| html-no-end: true
#| html-indent-lines: true
#| html-line-number: false
#| html-comment-delimiter: "//"
#| pdf-line-number: false
#| pdf-no-end: true
#| pdf-indent-lines: true
#| pdf-italic-comment: true
#| pdf-right-comment: true
#| pdf-comment-color: "darkgray"
#| pdf-comment-delimiter: "//"
#| pdf-placement: "ht!"

\begin{algorithmic}
\Function{MonotoneQueue}{$w, \texttt{vals}$}
    \State{$\texttt{queue} \gets$ empty \textsc{DoubleEndedQueue}}
    \For{$i$ in $\{0, \ldots, |\texttt{vals}| - 1\}$}
        \If{$\texttt{queue.front().pos} + w \leq i$}
            \State{\texttt{queue.pop\_front()}}
        \EndIf
        \While{$\texttt{queue.back.val} > \texttt{vals}[i]$}
            \State{\texttt{queue.pop\_back()}}
        \EndWhile
        \State{$\texttt{queue.push\_back}(\texttt{val}
            \gets  \texttt{vals}[i], \texttt{pos} \gets i)$}
        \If{$i \geq w-1$}
            \State{\textbf{yield} $\texttt{queue.front().pos}$}
        \EndIf
    \EndFor
\EndFunction
\end{algorithmic}
```

Monotone queue algorithm for sliding window minimum
:::

### Rescan

Another approach used in bioinformatics is to only keep track of the minimum value and rescan the entire window of $w$ values when the current minimum goes out of scope, as described in @alg-sliding-min-rescan.
For instance, this is the method used in minimap2 [@minimap2].
While this algorithm does not guarantee a worst-case constant time update, it only branches when the minimum goes out of scope and hence is more predictable.
This makes it more efficient in practice, especially since minimizers typically have a density of $\mathcal{O}(1/w)$ so that the $\mathcal{O}(w)$ rescan step takes amortized constant time per element.

::: {#alg-sliding-min-rescan}

```pseudocode
#| html-no-end: true
#| html-indent-lines: true
#| html-line-number: false
#| html-comment-delimiter: "//"
#| pdf-line-number: false
#| pdf-no-end: true
#| pdf-indent-lines: true
#| pdf-italic-comment: true
#| pdf-right-comment: true
#| pdf-comment-color: "darkgray"
#| pdf-comment-delimiter: "//"
#| pdf-placement: "ht!"

\begin{algorithmic}
\Function{Rescan}{$w, \texttt{vals}$}
    \State{$\texttt{min\_val} \gets +\infty$}
    \State{$\texttt{min\_pos} \gets 0$}
    \For{$i$ in $\{0, \ldots, |\texttt{vals}| - 1\}$}
        \If{$\texttt{vals}[i] < \texttt{min\_val}$}
            \State{$\texttt{min\_val} \gets \texttt{vals}[i]$}
            \State{$\texttt{min\_pos} \gets i$}
        \EndIf
        \If{$\texttt{min\_pos} + w \leq i$}
            \State{$\texttt{min\_pos} \gets \arg \min \{\texttt{vals}[i-w+1], \ldots, \texttt{vals}[i]\}$}
            \State{$\texttt{min\_val} \gets \texttt{vals}[\texttt{min\_pos}]$}
        \EndIf
        \If{$i \geq w-1$}
            \State{\textbf{yield} $\texttt{min\_pos}$}
        \EndIf
    \EndFor
\EndFunction
\end{algorithmic}
```

Rescan algorithm for sliding window minimum
:::

:::{#tbl-algos-sliding-min .large-table}
| Algorithm | Time complexity | Branches |
|:---:|:-------:|:----:|
| Naive | $\mathcal{O}(nw)$ worst-case | branchless |
| Rescan | $\mathcal{O}(nw)$ worst-case, $\mathcal{O}(n)$ on average | branch for each rescan |
| Monotone queue | $\mathcal{O}(n)$ worst-case | branch for each update |

Comparison of the naive, rescan and monotone queue sliding window minimum algorithms.
:::

## A branchless linear algorithm using two stacks

## Computing canonical minimizers {#sec-canonical-minimizers}

## Vectorized implementation

Branchless computation of the minimum in a sliding window of size $w$
(in practice $w$ /kmer hashes)

::: {#alg-sliding-min}

```pseudocode
#| html-no-end: true
#| html-indent-lines: true
#| html-line-number: false
#| html-comment-delimiter: "//"
#| pdf-line-number: false
#| pdf-no-end: true
#| pdf-indent-lines: true
#| pdf-italic-comment: true
#| pdf-right-comment: true
#| pdf-comment-color: "darkgray"
#| pdf-comment-delimiter: "//"
#| pdf-placement: "ht!"

\begin{algorithmic}
\Function{SlidingMin}{$w, \texttt{hash\_it}$}
    \Comment{\texttt{hash\_it} iterates over 32-bit hashes of each k-mer.}
    \State{$\texttt{val\_mask} \gets \texttt{0xffff0000}$}
    \Comment{Use high 16 bits of each value.}
    \State{$\texttt{pos\_mask} \gets \texttt{0x0000ffff}$}
    \Comment{Low 16 bits store positions.}
    \State{$\texttt{prefix\_min} \gets \texttt{0xffffffff}$}
    \State{$\texttt{suffix\_min} \gets$ buffer of size $w$ filled with $\texttt{0xffffffff}$}
    \State{$n \gets |\texttt{hash\_it}| - w - 1$}
    \Comment{The first $w-1$ hashes do not complete a window.}
    \State{$i \gets \texttt{LANE\_IDX} \times n$}
    \Comment{Current position of the lane.}
    \State{$j \gets 0$}
    \For{$h$ in $\texttt{hash\_it}$}
        \State{$\texttt{val} \gets (h \texttt{ \& val\_mask}) \texttt{ | i}$}
        \State{$\texttt{prefix\_min} \gets \min(\texttt{prefix\_min}, \texttt{val})$}
        \State{$\texttt{suffix\_min}[j] \gets \texttt{val}$}
        \Comment{Write the current value into the buffer.}
        \State{$j \gets j + 1$}
        \If{$j = w$}
        \Comment{When the buffer is full, recompute suffix minima.}
            \State{$j \gets 0$}
            \State{$\texttt{prefix\_min} \gets \texttt{0xffffffff}$}
            \For{$k$ in $\{w-2, w-3, \ldots, 0\}$}
                \State{$\texttt{suffix\_min}[k] \gets \min(\texttt{suffix\_min}[k], \texttt{suffix\_min}[k+1])$}
            \EndFor
        \EndIf
        \If{$i \ge \texttt{LANE\_IDX} \times n + w-1$}
        \Comment{Skip the first $w-1$ incomplete windows.}
            \State{\textbf{yield} $\min(\texttt{prefix\_min}, \texttt{suffix\_min}[j]) \texttt{ \& pos\_mask}$}
        \EndIf
        \State{$i \gets i + 1$}
    \EndFor
\EndFunction
\end{algorithmic}
```

Sliding min using two stacks
:::

## Variations and practical use
