# Useful tools {#sec-useful-tools}

I wanted to take this thesis as an opportunity to share some tools that I found particularly useful during my PhD.

## Typesetting this thesis

I decided early on to use [Quarto](https://quarto.org/) to typeset this thesis.
Looking back, I think this was a great choice for multiple reasons:

- I find its (enriched) Markdown syntax to be much nicer to use than LaTeX, and it helped me focus on the content itself.
- Having a live web version that gets instantly updated as you type is incredibly convenient compared to the long compilation time of LaTeX.
- It still provides fine-grained control of [figures](https://quarto.org/docs/authoring/figures.html) and [references](https://quarto.org/docs/authoring/cross-references.html), and supports many [themes](https://quarto.org/docs/gallery/) and [extensions](https://quarto.org/docs/extensions/).
- Because it is built on top of [Pandoc](https://pandoc.org/), it can export a wide variety of formats, which is what let me have a web version and a PDF produced with the same sources.

You can find all the sources of this thesis alongside the extensions I tweaked at <https://github.com/imartayan/phd>.

## Bibliography management and formatting

The main solution I use to manage my collection of articles is [Zotero](https://www.zotero.org/), I find it easy to use and its built-in [PDF annotation tool](https://www.zotero.org/support/pdf_reader) is very convenient.
If you feel limited by its storage sync limit of 300 MB, note that you can actually use [any WebDAV server](https://www.zotero.org/support/sync) to sync your files instead.
For instance, if your institution has a Nextcloud server, you can use it to sync larger collections.
They also recently made an iOS/Android app to access your collection, which can be useful if you prefer using a tablet.

While writing this thesis, I very often needed to add BibTeX entries for new articles.
At first I was using Google Scholar to do that, but I quickly noticed that its entries were often incomplete and that it systematically stripped DOIs, which is the most important information in my opinion.
Thus I decided to write my own tool called [bibelot](https://github.com/imartayan/bibelot) (*bib a lot*) to do that.
It's a CLI tool that takes DOIs or preprint links as input, fetches up-to-date metadata, and copies the resulting BibTeX entries to a file or to your clipboard.

## CLI tools I use everyday

I spend most of time working from a terminal, and there are a few tools that I couldn't live without:

- First for the terminal itself, [Ghostty](https://ghostty.org/) is a very nice piece of software, fast and very polished.
- When working on a remote server, [bottom](https://github.com/ClementTsang/bottom) is a great replacement for `top` to monitor processes and resource usage.
- If you need to monitor disk usage, [dust](https://github.com/bootandy/dust) is a great replacement for `du`.
- When searching for a pattern inside text files, [ripgrep](https://github.com/BurntSushi/ripgrep) is usually much faster than `grep`.
- Ripgrep can actually be extended with [ripgrep-all](https://github.com/phiresky/ripgrep-all) to search many other formats such as PDF. This allows me to search for a keyword in my entire collection of articles in a couple seconds.

## Rust toolchain

These days, I write most of my code in Rust and in addition to the built-in toolchain, there are a few more tools that I find very convenient:

- While the warning messages of the compiler are already very useful, [clippy](https://github.com/rust-lang/rust-clippy) provides even more suggestions and can even automatically apply fixes. You can also set up your favorite editor to integrate clippy warnings to your code.
- I don't always notice when my dependencies are outdated, and [cargo-outdated](https://github.com/kbknapp/cargo-outdated) can check for that automatically.
- Similarly, [cargo-machete](https://github.com/bnjbvr/cargo-machete) lets you remove unused dependencies.
- Flame graphs are a great way to visualize the trace of your program to identify which functions dominate the running time, you can easily generate them with [cargo-flamegraph](https://github.com/flamegraph-rs/flamegraph).
- Sometimes flame graphs are not enough and you want to look at the assembly generated for a specific function, this can be done with [cargo-show-asm](https://github.com/pacak/cargo-show-asm). This is especially useful to understand what the compiler is doing behind your back.
- Finally, if you end publishing crates, [cargo-release](https://github.com/crate-ci/cargo-release) provides many sanity checks before actually doing the release.

You can install all these tools using the following commands:
```sh
rustup update
rustup component add clippy
cargo install cargo-outdated cargo-machete flamegraph cargo-show-asm cargo-release
```
