on:
  workflow_dispatch:
  push:
    branches:
      - main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write # needed for Cloudflare
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
          cache: "pip"

      - name: Install Python dependencies
        run: python -m pip install -r requirements.txt

      - name: Cache TinyTeX
        id: cache-tinytex
        uses: actions/cache@v5
        with:
          path: ~/.TinyTeX
          key: tinytex-${{ runner.os }}-dvisvgm-pgf-standalone

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: ${{ steps.cache-tinytex.outputs.cache-hit != 'true' }}

      - name: Set up TinyTeX
        if: steps.cache-tinytex.outputs.cache-hit != 'true'
        run: tlmgr install dvisvgm pgf standalone

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html

      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: imartayan-phd
          directory: "_book"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
